adqp/api/urls.py
from django.urls import path
from .views import MarketFieldsView, QueryView
from django.urls import path, include
urlpatterns = [

    # List and Create
    path('market-fields/', MarketFieldsView.as_view(), name='market-fields-list'),  # For GET and POST
    # Detail, Update, and Delete by pk
    path('market-fields/<int:pk>/', MarketFieldsView.as_view(), name='market-fields-detail'),  # For PUT and DELETE

    path('query/', QueryView.as_view(), name='query'),  # For Query market fields
]

adqp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import query_db1b_data
app_name = "adqp"
urlpatterns = [
    path('', views.home_page, name="home-page"),

    path('query/', query_db1b_data, name='query_db1b_data'),
    # Other URLs
    path('api/', include('adqp.api.urls')),  # Include API URLs


    path('text-to-sql', views.text_to_sql_view, name="text-to-sql"),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path("/", include('adqp.urls')),
    path("admin/", admin.site.urls),
    # The web page start from the properties/
    path('adqp/', include('adqp.urls', namespace="adqp")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adqp/aitools_autogen/blueprint.py
from typing import Optional

from autogen import ConversableAgent


class Blueprint:

    def __init__(self,
                 agents: Optional[list[ConversableAgent]] = None,
                 config_list: Optional[list[dict]] = None,
                 llm_config: Optional[dict] = None):
        self._agents = agents or None
        self._config_list = config_list or None
        self._llm_config = llm_config or None

        self._initiator = agents[0] if agents else None
        self._recipient = agents[1] if agents and len(agents) > 1 else None

    async def initiate_work(self, message: str):
        if self._initiator and self._recipient:
            self._initiator.initiate_chat(recipient=self._recipient, message=message)
        else:
            raise ValueError("No initiator or recipient agent found.")

adqp/aitools_autogen/blueprint_generate_core_client.py
from typing import Optional

import aitools_autogen.utils as utils
from aitools_autogen.agents import WebPageScraperAgent
from aitools_autogen.blueprint import Blueprint
from aitools_autogen.config import llm_config_openai as llm_config, config_list_openai as config_list, WORKING_DIR
from autogen import ConversableAgent

class CoreClientTestBlueprint(Blueprint):

    def __init__(self, work_dir: Optional[str] = WORKING_DIR):
        super().__init__([], config_list=config_list, llm_config=llm_config)
        self._work_dir = work_dir or "code"
        self._summary_result: Optional[str] = None

    @property
    def summary_result(self) -> str | None:
        """The getter for the 'summary_result' attribute."""
        return self._summary_result

    @property
    def work_dir(self) -> str:
        """The getter for the 'work_dir' attribute."""
        return self._work_dir

    async def initiate_work(self, message: str):
        utils.clear_working_dir(self._work_dir)
        agent0 = ConversableAgent("a0",
                                  max_consecutive_auto_reply=0,
                                  llm_config=False,
                                  human_input_mode="NEVER")

        scraper_agent = WebPageScraperAgent()

        summary_agent = ConversableAgent("summary_agent",
                                         max_consecutive_auto_reply=6,
                                         llm_config=llm_config,
                                         human_input_mode="NEVER",
                                         code_execution_config=False,
                                         function_map=None,
                                         system_message="""You are a helpful AI assistant.
     You are a helpful AI assistant. Your task is to summarize 
                                         the dataset information from the website. List the dataset fields and their datatype. 
                                         clarity. Return `None` if the input is invalid or not sufficient to generate 
                                         a summary.

        Return `None` if the message or url  is not valid or cannot be summarized.
            """)

        aiohttp_client_agent = ConversableAgent("aiohttp_client_agent",
                                                max_consecutive_auto_reply=6,
                                                llm_config=llm_config,
                                                human_input_mode="NEVER",
                                                code_execution_config=False,
                                                function_map=None,
                                                system_message="""
           You are a web developer using Postgresql and Django. You are developing an application which use some sort of data. When you are receiving a message or URL, assuming it is an official documentation from the dataset's uploader. You need to read all information from this website, so that you can understand the data. You're writing script code and Python to set up a PostgreSQL database with Django. According to the documentation, you will have idea about what the data is about and how the dataset is formed.
        Assuming you already download the review data, and the database table is set up properly.  
        You need to generate Django model code based on a defined schema and create a complementary utilities.py file containing helper functions relevant to the operations, validations, or transformations that the models might require.
        
        Here are some key points to consider:
        
1. Model Generation

The system should parse input (such as JSON, YAML, or direct database schemas) to create Django model classes. These models will include fields, relationships (like ForeignKey or ManyToManyField), and methods like custom save operations or property methods.

2. Utilities.py Generation

This file should include functions that can be used across the application, especially those that relate to the data managed by the models. Typical functions might include data validators, transformation utilities, or more complex business logic that doesn't belong directly in the model or view layers.


3. Integration with Django Admin:

    Auto-generate Django admin configurations for each model to provide a robust interface for data management right out of the box.


    Use multiple classes in separate file names in a directory structure that makes sense.
        Use aiohttp.ClientSession for the http client.
        Use aiohttp.ClientResponse for the http response.

        Create the aiohttp session inside a `with` block so that it is closed automatically.
        The code using this generated code should not require aiohttp.

        You must indicate the script type in the code block.
        Do not suggest incomplete code which requires users to modify.
        Always put `# filename: <filename>` as the first line of each code block.

        Feel free to include multiple code blocks in one response. Do not ask users to copy and paste the result.



        
        """)

        agent0.initiate_chat(scraper_agent, True, True, message=message)

        message = agent0.last_message(scraper_agent)

        agent0.initiate_chat(summary_agent, True, True, message=message)

        api_description_message = agent0.last_message(summary_agent)

        # api_description = api_description_message["content"]
        # print(api_description)

        agent0.initiate_chat(aiohttp_client_agent, True, True, message=api_description_message)

        llm_message = agent0.last_message(aiohttp_client_agent)["content"]
        utils.save_code_files(llm_message, self.work_dir)

        self._summary_result = utils.summarize_files(self.work_dir)

adqp/aitools_autogen/blueprint_project8.py
from typing import Optional

import aitools_autogen.utils as utils
from aitools_autogen.agents import WebPageScraperAgent
from aitools_autogen.blueprint import Blueprint
from aitools_autogen.config import llm_config_openai as llm_config, config_list_openai as config_list, WORKING_DIR
from autogen import ConversableAgent


class CoreClientProject8(Blueprint):

    def __init__(self, work_dir: Optional[str] = WORKING_DIR):
        super().__init__([], config_list=config_list, llm_config=llm_config)
        self._work_dir = work_dir or "code"
        self._summary_result: Optional[str] = None

    @property
    def summary_result(self) -> str | None:
        """The getter for the 'summary_result' attribute."""
        return self._summary_result

    @property
    def work_dir(self) -> str:
        """The getter for the 'work_dir' attribute."""
        return self._work_dir

    async def initiate_work(self, message: str):
        utils.clear_working_dir(self._work_dir)
        agent0 = ConversableAgent("a0",
                                  max_consecutive_auto_reply=0,
                                  llm_config=False,
                                  human_input_mode="NEVER")

        scraper_agent = WebPageScraperAgent()

        summary_agent = ConversableAgent("summary_agent",
                                         max_consecutive_auto_reply=6,
                                         llm_config=llm_config,
                                         human_input_mode="NEVER",
                                         code_execution_config=False,
                                         function_map=None,
                                         system_message="""You are a helpful AI assistant. Your task is to summarize 
                                         the dataset information from the website. List the dataset fields and their datatype. 
                                         clarity. Return `None` if the input is invalid or not sufficient to generate 
                                         a summary.

        Return `None` if the message or url  is not valid or cannot be summarized.
            """)

        aiohttp_client_agent = ConversableAgent("aiohttp_client_agent",
                                                max_consecutive_auto_reply=6,
                                                llm_config=llm_config,
                                                human_input_mode="NEVER",
                                                code_execution_config=False,
                                                function_map=None,
                                                system_message="""
         You are a web developer using Postgresql and Django. You are developing an application which use some sort of data. When you are receiving a message or URL, assuming it is an official documentation from the dataset's uploader. You need to read all information from this website, so that you can understand the data. You're writing script code and Python to set up a PostgreSQL database with Django. According to the documentation, you will have idea about what the data is about and how the dataset is formed.
        Assuming you already download the review data, and the database table is set up properly.  
        You need to generate Django model code based on a defined schema and create a complementary utilities.py file containing helper functions relevant to the operations, validations, or transformations that the models might require.
        
        Here are some key points to consider:
        
1. Model Generation

The system should parse input (such as JSON, YAML, or direct database schemas) to create Django model classes. These models will include fields, relationships (like ForeignKey or ManyToManyField), and methods like custom save operations or property methods.

2. Utilities.py Generation

This file should include functions that can be used across the application, especially those that relate to the data managed by the models. Typical functions might include data validators, transformation utilities, or more complex business logic that doesn't belong directly in the model or view layers.


3. Integration with Django Admin:

    Auto-generate Django admin configurations for each model to provide a robust interface for data management right out of the box.


    Use multiple classes in separate file names in a directory structure that makes sense.
        Use aiohttp.ClientSession for the http client.
        Use aiohttp.ClientResponse for the http response.

        Create the aiohttp session inside a `with` block so that it is closed automatically.
        The code using this generated code should not require aiohttp.

        You must indicate the script type in the code block.
        Do not suggest incomplete code which requires users to modify.
        Always put `# filename: <filename>` as the first line of each code block.
        
        The models should be in the model folder, for the models, always put `# filename: models/<filename>` as the first line of each code block.

        Feel free to include multiple code blocks in one response. Do not ask users to copy and paste the result.


        """)

        agent0.initiate_chat(scraper_agent, True, True, message=message)

        message = agent0.last_message(scraper_agent)

        agent0.initiate_chat(summary_agent, True, True, message=message)

        api_description_message = agent0.last_message(summary_agent)

        api_description = api_description_message["content"]
        print(api_description)

        agent0.initiate_chat(aiohttp_client_agent, True, True, message=api_description_message)

        llm_message = agent0.last_message(aiohttp_client_agent)["content"]
        # print(llm_message)
        utils.save_code_files(llm_message, self.work_dir)

        self._summary_result = utils.summarize_files(self.work_dir)
        print(utils.summarize_files(WORKING_DIR))


if __name__ == "__main__":
    import asyncio

    blueprint = CoreClientProject8()
    message = "https://amazon-reviews-2023.github.io/"  # Replace with your actual message

    asyncio.run(blueprint.initiate_work(message))
    print(blueprint.summary_result)

templates/adqp/all_trips.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADQP</title>
</head>
<body>
    <h1>All trip data</h1>
    <p>Here is the list of all trips</p>

    <h2>List of trips</h2>
    <ul>
    {% for trip in trips %}
<ul>
    {% for trip in trips %}
        <li>{{ trip.id }} - {{ trip.ORIGIN_AIRPORT_ID }} - {{ trip.ORIGIN_AIRPORT_SEQ_ID }} - {{ trip.ORIGIN_CITY_MARKET_ID }} - {{ trip.DEST_AIRPORT_ID }} - {{ trip.DEST_AIRPORT_SEQ_ID }} - {{ trip.DEST_CITY_MARKET_ID }}</li>
    {% endfor %}
</ul>

      
    {% endfor %}
</ul>

</body>
</html>

templates/adqp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADQP | {% block page-title %}{% endblock %} </title>
    <link rel="stylesheet" type="text/css" href={% static "css/responsive.css" %}>

    <script src={% static "js/jquery-3.7.1.min.js" %}></script>
    <script src={% static "js/script.js" %}></script>
    <meta name="viewport" content="width=device-width">
</head>
<body>

<div id="header">


    <div id="logo-box">
        <!--        The logo is made from a free logo making website https://www.canva.com/create/logos/-->
{#        {% if  request.session.username%}#}
{#            <a href="{% url 'adqp:user-home' %}"><img id="logo" alt="logo" src={% static "img/logo.png"%}/></a>#}
{#        {% else %}#}
{#             <a href="{% url 'adqp:home-page' %}"><img id="logo" alt="logo" src={% static "img/logo.png"%}/></a>#}
{#        {% endif %}#}

        <div id="title-box">
            <h1>NoVA Renting</h1>
            <h2>A site for helping international student</h2>

        </div>


        <!-- Search Bar -->


    </div>


    <div class="search-bar-div">
        <form action="{% url "adqp:search-result" %}" class="search-box" method="get">

            <input type="text" name="search-property" class="search-bar" placeholder="Enter a property name"/>

            <!--             Search bottom -->
            <button type="submit" name="submit" value="Go" class="search-button">
                <img class="search-icon" src={% static "img/search-icon.svg"%} alt="Search" width="24" height="24"/>
            </button>

        </form>
    </div>





    <!--    nav bar -->
    <div id="primary-nav">
{#    {% if request.session.username %}#}
{#        <a href="{% url "adqp:user-home" %}">Home</a>#}
{#    {% else %}#}
        <a href="{% url "adqp:home-page" %}" class="nav-link-home">Home</a>
{#    {% endif %}#}



        <a href="{% url "adqp:properties-list" %}" class="nav-link-list">List</a>
{#    {% if request.session.username %}#}
        <a href="{% url "adqp:post-property-page" %}" class="nav-link-post">Post</a>
{#    {% else %}#}
{#        <a href="{% url "adqp:log-in-page" %}">Post</a>#}
{#    {% endif %}#}

        <a href="{% url "adqp:about" %}" class="nav-link-about">About</a>
        {% if request.session.username %}
            <a href="{% url 'users:profile' request.session.username%}">(<strong>{{ request.session.username }}</strong>) Profile </a>
               <a href="{% url 'users:logout'%}"> Log Out </a>

        {% else %}
         <a href="{% url "users:log-in-page" %}"  class="nav-link-login">Log In</a>
        {% endif %}
    </div>


</div> <!-- #header -->




<div id="content">
{% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

{% block content %}{% endblock %}


</div>


<div id="footer">



    <p id="footer-nav">
{#        {% if  request.session.username%}#}
{#            <a href="{% url 'adqp:user-home' %}">Home</a>#}
{#        {% else %}#}
             <a href="{% url 'adqp:home-page' %}">Home</a>
{#        {% endif %}#}
        | <a href="{% url 'adqp:properties-list' %}">List</a> | <a  href="{% url "adqp:about" %}">About</a> |
        <a href="#">Contact Us</a></p>
    <p id="copyright">Copyright 2023 RICHVA Inc.</p>

</div>


</body>
</html>

templates/adqp/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADQP</title>
</head>
<body>
    <h1>The Airline Data Query Platform (ADQP)</h1>
    <p>The Airline Data Query Platform (ADQP) aims to build an advanced query system that enables analysts to easily retrieve and analyze U.S. domestic airline ticket data from the DB1B dataset.</p>


</body>
</html>